# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('primary', '初级'), ('intermediate', '中级'), ('advanced', '高级')], max_length=20, verbose_name='课程难度'),
        ),
    ]
