# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180205_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='访问地址'),
        ),
    ]
