# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-15 20:06
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180215_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default=0, verbose_name='详情'),
        ),
    ]
