# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-16 10:39
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180216_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='详情'),
        ),
    ]
