# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-31 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180123_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='image/%Y/%m'),
        ),
    ]
