# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180210_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/2018/02/default_middile_8.png', upload_to='image/%Y/%m'),
        ),
    ]
